name: Build and Publish


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew shadowJar

      - name: Prepare files
        run: |
          mv build/libs/KotlinTelegramBot-1.0-SNAPSHOT-all.jar bot.jar
          
      - name: Check files
        run: |
          ls -la  bot.jar words.txt

      - name: Deploy JAR + words.txt
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "bot.jar words.txt"
          target: "/opt/english_bot/"


      - name: Set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo chown -R botuser:botuser /opt/english_bot
            sudo chmod 750 /opt/english_bot/bot.jar
            sudo chmod 640 /opt/english_bot/words.txt 

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart english-learning-bot